In [1]:
# Set up the file path
import os
os.chdir('..')

In [2]:
# Import packages
from RL4CRN.iocrns.reaction_library import construct_hill_production_library, construct_mass_action_library

In [3]:
species_labels = ['X_1', 'X_2', 'X_3']
n = len(species_labels)
P = 1
R = 2
O = 1
library = construct_hill_production_library(species_labels, max_product_order=P, max_num_regulators=R)
library_temp = construct_mass_action_library(species_labels, order=O)
print(library)
print("------------------------")
print(library_temp)
print("------------------------")
library.merge(library_temp)
print(library)


Number of reactions: 54
R0: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_1(None, 1))]
R1: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_2(None, 1))]
R2: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_3(None, 1))]
R3: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = X_1(None, 1);    (Kr, nr) = )]
R4: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = X_2(None, 1);    (Kr, nr) = )]
R5: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = X_3(None, 1);    (Kr, nr) = )]
R6: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_1(None, 1), X_2(None, 1))]
R7: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_1(None, 1), X_3(None, 1))]
R8: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = ;    (Kr, nr) = X_2(None, 1), X_3(None, 1))]
R9: ∅ ----> X_1;  [HILLProd(b = None, Vm = None,    (Ka, na) = X_1(None, 1);    (Kr, nr)

In [4]:
# Construct the continuous parameter mask
continuous_parameter_mask = library.get_parameter_mask(mode='continuous', force=False)
print("Continuous parameter mask:")
print(f"Type: {type(continuous_parameter_mask)}, Shape: {continuous_parameter_mask.shape}, dtype:, {continuous_parameter_mask.dtype}")
print(continuous_parameter_mask)

Continuous parameter mask:
Type: <class 'numpy.ndarray'>, Shape: (67, 4), dtype:, float32
[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0.

In [5]:
# # Construct the discrete parameter mask
# discrete_parameter_mask = library.get_parameter_mask(mode='discrete', force=False)
# print("Discrete parameter mask:")
# print(f"Type: {type(discrete_parameter_mask)}, Shape: {discrete_parameter_mask.shape}, dtype:, {discrete_parameter_mask.dtype}")
# print(discrete_parameter_mask)  

In [6]:
# # Construct the logits mask
# logit_mask = library.get_logit_mask()
# print("Logit mask:")
# print(f"Type: {type(logit_mask)}, Shape: {logit_mask.shape}, dtype:, {logit_mask.dtype}")
# print(logit_mask)