In [1]:
# Setting up the file path
import sys
import os
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

In [2]:
# Import packages and modules
import numpy as np
from RL4CRN_Feedback.Input_Output_Rxn_Networks.IOCRN_MassAction import IOCRN_MassAction

In [3]:
# Construct the basic CRN
species_labels = ['X_1', 'X_2', 'X_3']
inputs_labels = ['u_1', 'u_2', 'u_3', 'u_4']
stoichiometry_reactants = np.array([[0], [1], [0]], dtype=np.int8)
stoichiometry_products = np.array([[1], [1], [0]], dtype=np.int8)
k = 1
parameters = np.array([k], dtype=np.float32)
input_influence_matrix = np.array([[0], [0], [0], [0]], dtype=np.int8)
outputs = np.array([1], dtype=np.int8)
IOCRN_0 = IOCRN_MassAction(stoichiometry_reactants, stoichiometry_products, parameters, input_influence_matrix, outputs, species_labels, inputs_labels)
gamma_1 = 1; mu = 10; theta = 1; eta = 0.1; a = 0.1

In [4]:
# Construct a CRN by adding species to the reaction network
IOCRN_1 = IOCRN_0.clone()
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 1, 'product1 index': 0, 'product2 index': 0, 'input influence index': 1, 'rate constant': gamma_1}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 0, 'product1 index': 0, 'product2 index': 2, 'input influence index': 2, 'rate constant': mu}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 1, 'product1 index': 1, 'product2 index': 3, 'input influence index': 3, 'rate constant': theta}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 2, 'reactant2 index': 3, 'product1 index': 0, 'product2 index': 0, 'input influence index': 0, 'rate constant': eta}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 2, 'reactant2 index': 2, 'product1 index': 3, 'product2 index': 3, 'input influence index': 4, 'rate constant': a}, mode='species index')
print('CRN 3:')
IOCRN_1.print_reactions()

CRN 3:
Inputs: ['u_1', 'u_2', 'u_3', 'u_4'] 
Species: ['X_1', 'X_2', 'X_3'] 
Output Species: ['X_1'] 
Reaction 0: X_2 -> X_1 + X_2 ; Rate Constant: 1.0 
Reaction 1: X_1 -> 0 ; Rate Constant: 1.0u_1 
Reaction 2: 0 -> X_2 ; Rate Constant: 10.0u_2 
Reaction 3: X_1 -> X_1 + X_3 ; Rate Constant: 1.0u_3 
Reaction 4: X_2 + X_3 -> 0 ; Rate Constant: 0.1 
Reaction 5: 2 X_2 -> 2 X_3 ; Rate Constant: 0.1u_4 



In [5]:
# Map stoichiometries to species
reactants_indices = IOCRN_1.map_stoichiometry_to_species(IOCRN_1.stoichiometry_reactants)
products_indices = IOCRN_1.map_stoichiometry_to_species(IOCRN_1.stoichiometry_products)
print('Reactants indices:')
print(reactants_indices)
print('Products indices:')
print(products_indices)

Reactants indices:
[[0 0 0 0 2 2]
 [2 1 0 1 3 2]]
Products indices:
[[1 0 0 1 0 3]
 [2 0 2 3 0 3]]
