In [1]:
# Setting up the file path
import sys
import os
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

In [2]:
# Import packages and modules
import numpy as np
from RL4CRN_Feedback.Input_Output_Rxn_Networks.IOCRN_MassAction import IOCRN_MassAction

In [3]:
# Construct the basic CRN
species_labels = ['X_1', 'X_2', 'X_3']
inputs_labels = ['u_1', 'u_2', 'u_3', 'u_4']
stoichiometry_reactants = np.array([[0], [1], [0]], dtype=np.int64)
stoichiometry_products = np.array([[1], [1], [0]], dtype=np.int64)
k = 1
parameters = np.array([k], dtype=np.float32)
input_influence_matrix = np.array([[0], [0], [0], [0]], dtype=np.int64)
outputs = np.array([1], dtype=np.int64)
IOCRN_0 = IOCRN_MassAction(stoichiometry_reactants, stoichiometry_products, parameters, input_influence_matrix, outputs, species_labels, inputs_labels)
gamma_1 = 1; mu = 10; theta = 1; eta = 0.1; a = 0.1
print('Initial CRN:')
IOCRN_0.print_reactions()
print('Reactions Indices:')
print(IOCRN_0.reactions_indices)
print('Reactions Indices Influenced by Inputs:')
print(IOCRN_0.list_influenced_reactions)

Initial CRN:
Inputs: ['u_1', 'u_2', 'u_3', 'u_4'] 
Species: ['X_1', 'X_2', 'X_3'] 
Output Species: ['X_1'] 
Reaction 0: X_2 -> X_1 + X_2 ; Rate Constant: 1.0 

Reactions Indices:
[23]
Reactions Indices Influenced by Inputs:
[array([], dtype=uint64), array([], dtype=uint64), array([], dtype=uint64), array([], dtype=uint64)]


In [4]:
# Construct a CRN by adding species to the reaction network
IOCRN_1 = IOCRN_0.clone()
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 1, 'product1 index': 0, 'product2 index': 0, 'input influence index': 1, 'rate constant': gamma_1}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 0, 'product1 index': 0, 'product2 index': 2, 'input influence index': 2, 'rate constant': mu}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 0, 'reactant2 index': 1, 'product1 index': 1, 'product2 index': 3, 'input influence index': 3, 'rate constant': theta}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 2, 'reactant2 index': 3, 'product1 index': 0, 'product2 index': 0, 'input influence index': 0, 'rate constant': eta}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 2, 'reactant2 index': 2, 'product1 index': 3, 'product2 index': 3, 'input influence index': 4, 'rate constant': a}, mode='species index')
IOCRN_1.add_reaction({'reactant1 index': 2, 'reactant2 index': 3, 'product1 index': 0, 'product2 index': 3, 'input influence index': 2, 'rate constant': a*2}, mode='species index')

print('CRN 1:')
IOCRN_1.print_reactions()
print('Reactions Indices:')
print(IOCRN_1.reactions_indices)
print('Reactions Indices Influenced by Inputs:')
print(IOCRN_1.list_influenced_reactions)

CRN 1:
Inputs: ['u_1', 'u_2', 'u_3', 'u_4'] 
Species: ['X_1', 'X_2', 'X_3'] 
Output Species: ['X_1'] 
Reaction 0: X_2 -> X_1 + X_2 ; Rate Constant: 1.0 
Reaction 1: X_1 -> 0 ; Rate Constant: 1.0u_1 
Reaction 2: 0 -> X_2 ; Rate Constant: 10.0u_2 
Reaction 3: X_1 -> X_1 + X_3 ; Rate Constant: 1.0u_3 
Reaction 4: X_2 + X_3 -> 0 ; Rate Constant: 0.1 
Reaction 5: 2 X_2 -> 2 X_3 ; Rate Constant: 0.1u_4 
Reaction 6: X_2 + X_3 -> X_3 ; Rate Constant: 0.2u_2 

Reactions Indices:
[23 10  2 15 73 72 76]
Reactions Indices Influenced by Inputs:
[array([10], dtype=uint64), array([ 2, 76], dtype=uint64), array([15], dtype=uint64), array([72], dtype=uint64)]


In [5]:
# Map stoichiometries to species and stoichiometries to complexes and stoichiometries to reactions
reactants_species_indices = IOCRN_1.map_stoichiometry_matrix_to_species(IOCRN_1.stoichiometry_reactants)
products_species_indices = IOCRN_1.map_stoichiometry_matrix_to_species(IOCRN_1.stoichiometry_products)
reactants_indices_from_stoichiometry = IOCRN_1.map_stoichiometry_to_complexes(IOCRN_1.stoichiometry_reactants)
products_indices_from_stoichiometry = IOCRN_1.map_stoichiometry_to_complexes(IOCRN_1.stoichiometry_products)
reactions_indices_from_stoichiometry = IOCRN_1.map_stoichiometry_to_reactions(IOCRN_1.stoichiometry_reactants, IOCRN_1.stoichiometry_products)

print('Reactants indices:')
print(reactants_species_indices)
print('Products indices:')
print(products_species_indices)
print('Reactants indices from stoichiometry:')
print(reactants_indices_from_stoichiometry)
print('Products indices from stoichiometry:')
print(products_indices_from_stoichiometry)
print('Reaction indices from stoichiometry:')
print(reactions_indices_from_stoichiometry)

reactions_indices_influenced_by_inputs_from_stoichiometry = IOCRN_1.map_input_influence_matrix_to_reactions(reactions_indices_from_stoichiometry, IOCRN_1.input_influence_matrix)
print('Reactions indices influenced by inputs from stoichiometry:')
print(reactions_indices_influenced_by_inputs_from_stoichiometry)

Reactants indices:
[[0 0 0 0 2 2 2]
 [2 1 0 1 3 2 3]]
Products indices:
[[1 0 0 1 0 3 0]
 [2 0 2 3 0 3 3]]
Reactants indices from stoichiometry:
[2 1 0 1 8 7 8]
Products indices from stoichiometry:
[5 0 2 6 0 9 3]
Reaction indices from stoichiometry:
[23 10  2 15 73 72 76]
Reactions indices influenced by inputs from stoichiometry:
[array([10], dtype=uint64), array([ 2, 76], dtype=uint64), array([15], dtype=uint64), array([72], dtype=uint64)]


In [6]:
# Map species to complexes and complexes to reactions and species to reactions
reactants_complexes_indices = np.zeros((IOCRN_1.num_reactions), dtype=np.int8)
products_complexes_indices = np.zeros((IOCRN_1.num_reactions), dtype=np.int8)
reactions_indices = np.zeros((IOCRN_1.num_reactions), dtype=np.int8)
reactions_indices_direct = np.zeros((IOCRN_1.num_reactions), dtype=np.int8)
for i in range(IOCRN_1.num_reactions):
    reactants_complexes_indices[i] = IOCRN_1.map_species_to_complex(reactants_species_indices[0,i], reactants_species_indices[1,i])
    products_complexes_indices[i] = IOCRN_1.map_species_to_complex(products_species_indices[0,i], products_species_indices[1,i])
    reactions_indices[i] = IOCRN_1.map_complexes_to_reaction(reactants_complexes_indices[i], products_complexes_indices[i])
    reactions_indices_direct[i] = IOCRN_1.map_species_to_reaction(reactants_species_indices[0,i], reactants_species_indices[1,i], products_species_indices[0,i], products_species_indices[1,i])

for i in range(IOCRN_1.num_reactions):
    print(f"Reaction {reactions_indices[i]}: \t C_{reactants_complexes_indices[i]} -> C_{products_complexes_indices[i]} \t X_{reactants_species_indices[0,i]} + X_{reactants_species_indices[1,i]} -> X_{products_species_indices[0,i]} + X_{products_species_indices[1,i]} \t Reaction (Direct): {reactions_indices_direct[i]}")

Reaction 23: 	 C_2 -> C_5 	 X_0 + X_2 -> X_1 + X_2 	 Reaction (Direct): 23
Reaction 10: 	 C_1 -> C_0 	 X_0 + X_1 -> X_0 + X_0 	 Reaction (Direct): 10
Reaction 2: 	 C_0 -> C_2 	 X_0 + X_0 -> X_0 + X_2 	 Reaction (Direct): 2
Reaction 15: 	 C_1 -> C_6 	 X_0 + X_1 -> X_1 + X_3 	 Reaction (Direct): 15
Reaction 73: 	 C_8 -> C_0 	 X_2 + X_3 -> X_0 + X_0 	 Reaction (Direct): 73
Reaction 72: 	 C_7 -> C_9 	 X_2 + X_2 -> X_3 + X_3 	 Reaction (Direct): 72
Reaction 76: 	 C_8 -> C_3 	 X_2 + X_3 -> X_0 + X_3 	 Reaction (Direct): 76


In [7]:
# Create a CRN from stoichiometries
IOCRN_2 = IOCRN_MassAction(IOCRN_1.stoichiometry_reactants, IOCRN_1.stoichiometry_products, IOCRN_1.parameters, IOCRN_1.input_influence_matrix, IOCRN_1.output_species, IOCRN_1.species_labels, IOCRN_1.inputs_labels)
print('Final CRN:')
IOCRN_2.print_reactions()
print('Reactions Indices:')
print(IOCRN_2.reactions_indices)
print('Reactions Indices Influenced by Inputs:')
print(IOCRN_2.list_influenced_reactions)

Final CRN:
Inputs: ['u_1', 'u_2', 'u_3', 'u_4'] 
Species: ['X_1', 'X_2', 'X_3'] 
Output Species: ['X_1'] 
Reaction 0: X_2 -> X_1 + X_2 ; Rate Constant: 1.0 
Reaction 1: X_1 -> 0 ; Rate Constant: 1.0u_1 
Reaction 2: 0 -> X_2 ; Rate Constant: 10.0u_2 
Reaction 3: X_1 -> X_1 + X_3 ; Rate Constant: 1.0u_3 
Reaction 4: X_2 + X_3 -> 0 ; Rate Constant: 0.1 
Reaction 5: 2 X_2 -> 2 X_3 ; Rate Constant: 0.1u_4 
Reaction 6: X_2 + X_3 -> X_3 ; Rate Constant: 0.2u_2 

Reactions Indices:
[23 10  2 15 73 72 76]
Reactions Indices Influenced by Inputs:
[array([10], dtype=uint64), array([ 2, 76], dtype=uint64), array([15], dtype=uint64), array([72], dtype=uint64)]
